export const ADD_MODEL = 'ADD_MODEL'
export const DELETE_MODEL = 'DELETE_MODEL'
export const UPDATE_MODEL = 'UPDATE_MODEL'
export const GET_MODEL = 'GET_MODEL'
export const RESORT_MODEL = 'RESORT_MODEL'
export const SET_ACTIVE_MODEL = 'SET_ACTIVE_MODEL'